--CREATE TABLE Price(
--    vehicleId INTEGER,
--    currency VARCHAR(200) NOT NULL,
--    price FLOAT NOT NULL
--);
--
--INSERT INTO PRICE (VEHICLE_ID,CURRENCY,PRICE) VALUES (1, 'INR', 570987.67);
--INSERT INTO PRICE (VEHICLE_ID,CURRENCY,PRICE) VALUES (2, 'INR', 580987.67);
--INSERT INTO PRICE (VEHICLE_ID,CURRENCY,PRICE) VALUES (3, 'INR', 590987.67);
--INSERT INTO PRICE (VEHICLE_ID,CURRENCY,PRICE) VALUES (4, 'INR', 670987.67);
--INSERT INTO PRICE (VEHICLE_ID,CURRENCY,PRICE) VALUES (5, 'INR', 770987.67);
--INSERT INTO PRICE (VEHICLE_ID,CURRENCY,PRICE) VALUES (6, 'INR', 870987.67);

--DROP TABLE Price;

Select * from Price;